// this file is generated by go-bin.go
package main

import (
	"bytes"
	"compress/bzip2"
	"io"
)

var storedFiles = map[string][]byte{
	"snippets/gossip.cfg": {66, 90, 104, 57, 49, 65, 89, 38, 83, 89, 72, 79, 128, 238, 0, 0, 52, 217, 128, 0, 16, 80, 3, 195, 144, 46, 70, 222, 0, 32, 0, 84, 37, 83, 245, 76, 153, 6, 4, 209, 232, 18, 83, 83, 212, 54, 136, 24, 128, 197, 36, 152, 25, 193, 194, 32, 138, 58, 6, 5, 128, 206, 161, 80, 53, 68, 131, 34, 16, 161, 176, 175, 102, 120, 88, 248, 113, 145, 52, 112, 123, 142, 222, 126, 222, 48, 163, 44, 244, 110, 141, 11, 185, 34, 156, 40, 72, 36, 39, 192, 119, 0},
}

func GetStored(fn string) (r io.Reader) {
	bb := bytes.NewBuffer(storedFiles[fn])
	r = bzip2.NewReader(bb)
	return
}
